version: '3.1'

services:

  db:
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: wordpress_database
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    # MariaDB image that supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    #  Uncomment if you want to use MySQL instead
    #image: mysql:8.0.27
    restart: always
    volumes:
      - 'wordpress-database:/var/lib/mysql'
      # Execute *.sql, *.sql.gz, *.sh e.g. import SQL dump
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  wordpress:
    container_name: wordpress_app
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        // Change domain name to local development
        define('WP_HOME', 'http://wordpress.localhost');
        define('WP_SITEURL', WP_HOME);

        // Enable logging to ./wp-content/debug.log
        define( 'WP_DEBUG_LOG', true );
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./wp-content/:/var/www/html/wp-content/
      - 'wordpress-app:/var/www/html'

volumes:
  wordpress-app:
  wordpress-database:
  
